version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  facesdetection-python:
    lang: python3-http
    handler: ./facesdetection-python
    image: facesdetection-python:latest

