version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  facesdetection-python:
    lang: python3-flask-debian
    handler: ./facesdetection-python
    image: martinezmario/facesdetection-python:latest

